version: 0.2
artifacts:
  files:
    - transformed.yaml
  type: zip
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade awscli
      - aws --version
  pre_build:
    commands:
      # - pip install virtualenv
      # - virtualenv /tmp/venv
      # - . /tmp/venv/bin/activate
      # - pip install -r requirements.txt
      # - pip install -r requirements-test.txt
      # - pip install 'chalice>=1.21.0,<1.22.0'
      - pip install pipenv
      - pipenv install
      - export VENV_HOME_DIR=$(pipenv --venv)
      - . $VENV_HOME_DIR/bin/activate
      # - export PYTHONPATH=.
  build:
    commands:
      - pytest tests/ || exit 1
  post_build:
    commands:
      - chalice package /tmp/packaged
      - aws cloudformation package --template-file /tmp/packaged/sam.json --s3-bucket ${APP_S3_BUCKET} --output-template-file transformed.yaml
