version: 0.1
artifacts:
  files:
    - transformed.yaml
  type: zip
phases:
  build:
    commands:
      - pip install --upgrade awscli
      - aws --version
      - pip install virtualenv
      - virtualenv /tmp/venv
      - . /tmp/venv/bin/activate
      - pip install -r requirements.txt
      - pip install -r requirements-test.txt
      - pip install 'chalice>=1.21.0,<1.22.0'
      - export PYTHONPATH=.
      - pytest tests/ -v || exit 1
      - chalice package /tmp/packaged
      - aws cloudformation package --template-file /tmp/packaged/sam.json --s3-bucket ${APP_S3_BUCKET} --output-template-file transformed.yaml
